// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PackingSlip.Domain;

namespace PackingSlip.Domain.Migrations
{
    [DbContext(typeof(PackingDbContext))]
    partial class PackingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PackingSlip.Domain.Entities.AgentCommission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AgentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("PackingSlipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AgentCommission","dbo");
                });

            modelBuilder.Entity("PackingSlip.Domain.Entities.CustomerMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ActivatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsUpgraded")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpgradedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CustomerMembership","dbo");
                });

            modelBuilder.Entity("PackingSlip.Domain.Entities.FreeProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("FreeProduct","dbo");
                });

            modelBuilder.Entity("PackingSlip.Domain.Entities.FreeProductChild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FreeProductId")
                        .HasColumnType("int");

                    b.Property<int>("FreeQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FreeProductId");

                    b.ToTable("FreeProductChild","dbo");
                });

            modelBuilder.Entity("PackingSlip.Domain.Entities.FreeProductParent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FreeProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("RequiredQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FreeProductId");

                    b.ToTable("FreeProductParent","dbo");
                });

            modelBuilder.Entity("PackingSlip.Domain.Entities.PackingSlipHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("ActivateMembership")
                        .HasColumnType("bit");

                    b.Property<string>("AgentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HasBook")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasPhysicalProduct")
                        .HasColumnType("bit");

                    b.Property<string>("PackingSlipNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("UpgradeMembership")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PackingSlipHeader","dbo");
                });

            modelBuilder.Entity("PackingSlip.Domain.Entities.PackingSlipItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<bool?>("IsFreeItem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackingSlipId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackingSlipId");

                    b.ToTable("PackingSlipItem","dbo");
                });

            modelBuilder.Entity("PackingSlip.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product","dbo");
                });

            modelBuilder.Entity("PackingSlip.Domain.Entities.FreeProductChild", b =>
                {
                    b.HasOne("PackingSlip.Domain.Entities.FreeProduct", "FreeProduct")
                        .WithMany("FreeProductChildren")
                        .HasForeignKey("FreeProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PackingSlip.Domain.Entities.FreeProductParent", b =>
                {
                    b.HasOne("PackingSlip.Domain.Entities.FreeProduct", "FreeProduct")
                        .WithMany("FreeProductParents")
                        .HasForeignKey("FreeProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PackingSlip.Domain.Entities.PackingSlipItem", b =>
                {
                    b.HasOne("PackingSlip.Domain.Entities.PackingSlipHeader", "PackingSlipHeader")
                        .WithMany("PackingSlipItems")
                        .HasForeignKey("PackingSlipId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
